# np.sort
Return a sorted copy a array.

In [3]:
import numpy as np
a = np.random.randint(1,100,10)
a

array([64, 72, 97, 25, 39, 21, 17,  7, 68, 12], dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[86, 30, 79, 81],
       [63, 38, 53, 89],
       [75, 31, 50, 16],
       [45, 52,  8, 96],
       [96, 35, 39, 32],
       [42, 64, 90, 97]], dtype=int32)

In [5]:
np.sort(a)

array([ 7, 12, 17, 21, 25, 39, 64, 68, 72, 97], dtype=int32)

In [6]:
# reverse sort
np.sort(a)[::-1]

array([97, 72, 68, 64, 39, 25, 21, 17, 12,  7], dtype=int32)

In [7]:
b

array([[86, 30, 79, 81],
       [63, 38, 53, 89],
       [75, 31, 50, 16],
       [45, 52,  8, 96],
       [96, 35, 39, 32],
       [42, 64, 90, 97]], dtype=int32)

In [8]:
np.sort(b,axis=0)    # axis=0 for column and axis=1 for rows

array([[42, 30,  8, 16],
       [45, 31, 39, 32],
       [63, 35, 50, 81],
       [75, 38, 53, 89],
       [86, 52, 79, 96],
       [96, 64, 90, 97]], dtype=int32)

In [9]:
np.sort(b,axis=1)

array([[30, 79, 81, 86],
       [38, 53, 63, 89],
       [16, 31, 50, 75],
       [ 8, 45, 52, 96],
       [32, 35, 39, 96],
       [42, 64, 90, 97]], dtype=int32)

In [10]:
b[2,1]

np.int32(31)

In [11]:
b = np.array([[54, 91, 98, 50],
       [41, 19, 36, 21],
       [15, 15, 10, 50],
       [24, 98, 40, 94],
       [44, 95, 39, 92],
       [20, 88, 59, 46]])
b

array([[54, 91, 98, 50],
       [41, 19, 36, 21],
       [15, 15, 10, 50],
       [24, 98, 40, 94],
       [44, 95, 39, 92],
       [20, 88, 59, 46]])

In [12]:
# Reverse sort in 2D
np.sort(b)[:,::-1]

array([[98, 91, 54, 50],
       [41, 36, 21, 19],
       [50, 15, 15, 10],
       [98, 94, 40, 24],
       [95, 92, 44, 39],
       [88, 59, 46, 20]])

In [13]:
np.sort(b)[:,::-1]

array([[98, 91, 54, 50],
       [41, 36, 21, 19],
       [50, 15, 15, 10],
       [98, 94, 40, 24],
       [95, 92, 44, 39],
       [88, 59, 46, 20]])

## np.append
The np.append() appends the value along the mentioned axies of end of array


In [14]:
# Append 1D ARRAY
np.append(a,92)

array([64, 72, 97, 25, 39, 21, 17,  7, 68, 12, 92])

In [15]:
# Append in 2D array
b

array([[54, 91, 98, 50],
       [41, 19, 36, 21],
       [15, 15, 10, 50],
       [24, 98, 40, 94],
       [44, 95, 39, 92],
       [20, 88, 59, 46]])

In [16]:
rand = np.random.randint(1,100,(3,4))
rand

array([[68,  1, 92, 72],
       [32, 74, 36, 19],
       [44, 62, 51, 66]], dtype=int32)

In [17]:
b

array([[54, 91, 98, 50],
       [41, 19, 36, 21],
       [15, 15, 10, 50],
       [24, 98, 40, 94],
       [44, 95, 39, 92],
       [20, 88, 59, 46]])

In [18]:
# append column
random_col = np.random.randint(1,100,(b.shape[0],1))
result = np.append(b, random_col, axis=1) # axis=1 is leye use ho raha hy que k yaha items rows k agy add ho rahy hain

print(result)


[[54 91 98 50 28]
 [41 19 36 21 38]
 [15 15 10 50 72]
 [24 98 40 94 78]
 [44 95 39 92 99]
 [20 88 59 46 29]]


In [12]:
# append row
random_col = np.random.randint(1, 100, (1,b.shape[1]))
result = np.append(b, random_col, axis=0)

print(result)


[[92 21 75 15]
 [51 12 33 55]
 [89 18 15 52]
 [24 64 26 22]
 [27 24 32 42]
 [95 44 41 19]
 [79 85 13 91]]


In [22]:
# append row using vstack
random_col = np.random.randint(1, 100, (1,b.shape[1]))
result = np.vstack((b, random_col))

print(result)

[[54 91 98 50]
 [41 19 36 21]
 [15 15 10 50]
 [24 98 40 94]
 [44 95 39 92]
 [20 88 59 46]
 [15 44 84 31]]


In [29]:
# append row using vstack
random_col = np.random.randint(1, 100, (b.shape[0], 1))
resul = np.hstack((b, random_col))

print(resul)

[[54 91 98 50 43]
 [41 19 36 21 30]
 [15 15 10 50 37]
 [24 98 40 94 35]
 [44 95 39 92 30]
 [20 88 59 46 22]]


# np.concatenate
np.concatenate funcation concatenate a sequance of arrays along an existing axis.

In [30]:
# concatenate as row
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
e = np.concatenate((c,d),axis=0)
e

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
# concateneate as columns
e = np.concatenate((c,d),axis=1)
e

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
with the help of unique method we can get the unique values from an array with the perameter in np.unique().

In [16]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [32]:
a

array([95, 80, 27, 29, 41, 19, 24, 52,  9, 83], dtype=int32)

In [18]:
a.shape

(10,)

In [19]:
np.expand_dims(a,axis=0).shape

(1, 10)

In [33]:
f = np.expand_dims(a,axis=1)
f

array([[95],
       [80],
       [27],
       [29],
       [41],
       [19],
       [24],
       [52],
       [ 9],
       [83]], dtype=int32)

#  np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [21]:
a

array([66, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [22]:
# get indexes through condition
np.where(a>50)

(array([0, 1, 3, 5, 7, 8, 9]),)

In [23]:
# replace values through where given condition
np.where(a>50,1,a)

array([ 1,  1, 14,  1,  7,  1, 16,  1,  1,  1], dtype=int32)

In [24]:
# replace even number through where
np.where(a%2==0,0,a)

array([ 0,  0,  0, 73,  7, 75,  0, 77,  0,  0], dtype=int32)

In [25]:
np.where(a==32,2,a)

array([66, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [35]:
marks = np.random.randint(1,100,10)
grades = np.where(
    marks >= 80, "A",
    np.where(marks >= 60, "B",
    np.where(marks >= 40,"c",
    "fail"))

)
print(grades)


['c' 'fail' 'B' 'fail' 'fail' 'c' 'B' 'A' 'fail' 'fail']


In [42]:
count_fail = (grades == 'fail').sum()
count_fail


np.int64(5)

In [48]:
z = np.where(grades == 'fail')
len(z)

1

In [39]:
print(grades)
count_fail = len(np.where(grades == 'fail')[0])
count_fail


['c' 'fail' 'B' 'fail' 'fail' 'c' 'B' 'A' 'fail' 'fail']


5

In [28]:
np.sum(grades == 'fail')

np.int64(4)

# np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [29]:
a

array([66, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [30]:
#give index number of max value in array
np.argmax(a)

np.int64(7)

In [31]:
b

array([[92, 21, 75, 15],
       [51, 12, 33, 55],
       [89, 18, 15, 52],
       [24, 64, 26, 22],
       [27, 24, 32, 42],
       [95, 44, 41, 19]], dtype=int32)

In [32]:
# max value through column 
np.argmax(b,axis=0)

array([5, 3, 0, 1])

In [33]:
# max value through row
np.argmax(b,axis=1)

array([0, 3, 0, 1, 3, 0])

In [34]:
# argmin small brother of argmax
np.argmin(a)

np.int64(4)

In [35]:
np.argmin(b,axis=0)

array([3, 1, 2, 0])

In [36]:
np.argmin(b,axis=1)

array([3, 1, 2, 3, 1, 3])

# np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [37]:
a

array([66, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [38]:
np.cumsum(a)

array([ 66, 138, 152, 225, 232, 307, 323, 400, 472, 548])

In [39]:
np.cumsum(a)

array([ 66, 138, 152, 225, 232, 307, 323, 400, 472, 548])

In [40]:
np.sum(a)

np.int64(548)

In [41]:
b

array([[92, 21, 75, 15],
       [51, 12, 33, 55],
       [89, 18, 15, 52],
       [24, 64, 26, 22],
       [27, 24, 32, 42],
       [95, 44, 41, 19]], dtype=int32)

In [42]:
np.cumsum(b)

array([ 92, 113, 188, 203, 254, 266, 299, 354, 443, 461, 476, 528, 552,
       616, 642, 664, 691, 715, 747, 789, 884, 928, 969, 988])

In [43]:
np.cumsum(b,axis=0)

array([[ 92,  21,  75,  15],
       [143,  33, 108,  70],
       [232,  51, 123, 122],
       [256, 115, 149, 144],
       [283, 139, 181, 186],
       [378, 183, 222, 205]])

In [44]:
np.cumsum(b,axis=1)

array([[ 92, 113, 188, 203],
       [ 51,  63,  96, 151],
       [ 89, 107, 122, 174],
       [ 24,  88, 114, 136],
       [ 27,  51,  83, 125],
       [ 95, 139, 180, 199]])

In [45]:
#cumprod
np.cumprod(a)

array([               66,              4752,             66528,
                 4856544,          33995808,        2549685600,
             40794969600,     3141212659200,   226167311462400,
       17188715671142400])

In [46]:
np.cumprod(b,axis=1)

array([[     92,    1932,  144900, 2173500],
       [     51,     612,   20196, 1110780],
       [     89,    1602,   24030, 1249560],
       [     24,    1536,   39936,  878592],
       [     27,     648,   20736,  870912],
       [     95,    4180,  171380, 3256220]])

# np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [47]:
a


array([66, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [48]:
np.percentile(a,50)

np.float64(72.0)

In [49]:
np.percentile(a,75)

np.float64(74.5)

# np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [50]:
a


array([66, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [51]:
histo = np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])
histo

(array([1, 2, 0, 0, 0, 0, 1, 6, 0, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

# np.corrcoef
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [52]:
salarys = np.array([20000,25000,20000,35000,40000])
experiance = np.arange(5)
np.corrcoef(salarys,experiance)

array([[1.        , 0.87038828],
       [0.87038828, 1.        ]])

# np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [53]:
a

array([66, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [54]:
# result boolen
items = [45,54,45,34,32,52,53,54]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False])

In [55]:
# result exit value
a[np.isin(a,items)]

array([], dtype=int32)

# np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [56]:
a

array([66, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [57]:
np.flip(a)

array([76, 72, 77, 16, 75,  7, 73, 14, 72, 66], dtype=int32)

In [58]:
b

array([[92, 21, 75, 15],
       [51, 12, 33, 55],
       [89, 18, 15, 52],
       [24, 64, 26, 22],
       [27, 24, 32, 42],
       [95, 44, 41, 19]], dtype=int32)

In [59]:
np.flip(b)

array([[19, 41, 44, 95],
       [42, 32, 24, 27],
       [22, 26, 64, 24],
       [52, 15, 18, 89],
       [55, 33, 12, 51],
       [15, 75, 21, 92]], dtype=int32)

In [60]:
np.flip(b,axis=0)

array([[95, 44, 41, 19],
       [27, 24, 32, 42],
       [24, 64, 26, 22],
       [89, 18, 15, 52],
       [51, 12, 33, 55],
       [92, 21, 75, 15]], dtype=int32)

In [61]:
np.flip(b,axis=1)

array([[15, 75, 21, 92],
       [55, 33, 12, 51],
       [52, 15, 18, 89],
       [22, 26, 64, 24],
       [42, 32, 24, 27],
       [19, 41, 44, 95]], dtype=int32)

# np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [62]:
a

array([66, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [63]:
np.put(a,[0],[70])

In [64]:
a[a == 6] = 10

# np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [65]:
a

array([70, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [66]:
np.delete(a,[1])

array([70, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [67]:
np.delete(a,np.where(a==91))

array([70, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [194]:
a

array([70, 45, 91, 32, 32, 10,  7, 19, 52, 38], dtype=int32)

# Set functions
np.union1d
np.intersect1d
np.setdiff1d
np.setxor1d
np.in1d

In [69]:
# union1d 
n = np.array([1,2,3,4,5,6])
m = np.array([1,2,3,7,8,9])
np.union1d(n,m)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
# np.intersect1d
np.intersect1d(n,m)

array([1, 2, 3])

In [71]:
np.setdiff1d(n,m)

array([4, 5, 6])

In [72]:
np.setdiff1d(m,n)

array([7, 8, 9])

In [73]:
np.setxor1d(n,m)

array([4, 5, 6, 7, 8, 9])

In [78]:
m[np.in1d(m,[4,7,8,3])]

C:\Users\HP\AppData\Local\Temp\ipykernel_27344\1705460229.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,[4,7,8,3])]


array([3, 7, 8])

In [79]:
m[np.isin(m,[4,7,8,3])]

array([3, 7, 8])

# np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html



In [80]:
a


array([70, 72, 14, 73,  7, 75, 16, 77, 72, 76], dtype=int32)

In [81]:
np.clip(a,a_min=10,a_max=50)

array([50, 50, 14, 50, 10, 50, 16, 50, 50, 50], dtype=int32)

# np.swapaxes
np.swapaxes() is used to swap (exchange) two axes of a NumPy array.
It works for 2D, 3D, or higher-dimensional arrays.

In [82]:
b

array([[92, 21, 75, 15],
       [51, 12, 33, 55],
       [89, 18, 15, 52],
       [24, 64, 26, 22],
       [27, 24, 32, 42],
       [95, 44, 41, 19]], dtype=int32)

In [84]:
np.swapaxes(b,0,1)

array([[92, 51, 89, 24, 27, 95],
       [21, 12, 18, 64, 24, 44],
       [75, 33, 15, 26, 32, 41],
       [15, 55, 52, 22, 42, 19]], dtype=int32)

In [93]:
c = np.random.randint(1,100,24).reshape(2,4,3)
d = c
d

array([[[26, 13, 41],
        [36, 92, 37],
        [31, 77, 14],
        [ 6, 97, 99]],

       [[43, 80, 26],
        [20,  2,  9],
        [97, 83, 71],
        [87, 11, 76]]], dtype=int32)

In [95]:
d

array([[[26, 13, 41],
        [36, 92, 37],
        [31, 77, 14],
        [ 6, 97, 99]],

       [[43, 80, 26],
        [20,  2,  9],
        [97, 83, 71],
        [87, 11, 76]]], dtype=int32)

In [100]:
d
np.swapaxes(d,1,2)

array([[[26, 36, 31,  6],
        [13, 92, 77, 97],
        [41, 37, 14, 99]],

       [[43, 20, 97, 87],
        [80,  2, 83, 11],
        [26,  9, 71, 76]]], dtype=int32)

# np.random.uniform() — clear & simple

np.random.uniform() is used to generate random numbers from a uniform distribution

In [102]:
e = np.random.uniform(1,100,10)
e

array([38.14954048, 59.37058242, 38.45194441,  4.26710819, 43.1573118 ,
       58.6366152 , 92.4133251 , 19.63388581, 44.60483309, 81.57844093])

In [107]:
d = np.random.uniform(1,50,(3,4))

In [104]:
d

array([[ 2.09123384, 35.53069161, 44.51016934, 29.82699598],
       [24.3462316 , 30.17028724,  4.14913479, 20.4973862 ],
       [46.75244439, 49.00922488, 28.2806515 , 32.7451017 ]])

# np.count_nonzero()
np.count_nonzero() counts how many non-zero (True) values are present in a NumPy array.

In [108]:
s = np.array([1,0,4,6,0,9,8])
s

array([1, 0, 4, 6, 0, 9, 8])

In [109]:
np.count_nonzero(s)

5

In [110]:
a1 = np.arange(0,50,10)
a1

array([ 0, 10, 20, 30, 40])

In [111]:
np.count_nonzero(a1>20)

2

In [113]:
a2 = np.arange(0,12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
np.count_nonzero(a2)

11

In [115]:
np.count_nonzero(a2,axis=0)

array([2, 3, 3, 3])

In [116]:
np.count_nonzero(a2,axis=1)

array([3, 4, 4])

# 21. np.tile
np.tile() is used to repeat an array multiple times along rows and/or columns.
https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [117]:
a3 = np.array([1,2,3,4])
a3

array([1, 2, 3, 4])

In [120]:
np.tile(a3,3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [121]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.tile(a2,2)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [124]:
np.tile(a2,(2,1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

 # np.repeat
np.repeat repeats elements of an array. You can specify how many times each element should be repeated.
https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [125]:
a3

array([1, 2, 3, 4])

In [127]:
np.repeat(a3,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [128]:
np.repeat(a3,[1,2,3,4])

array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

In [129]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
np.repeat(a2,2,axis=0)

array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [133]:
np.repeat(a2,2,axis=1)

array([[ 0,  0,  1,  1,  2,  2,  3,  3],
       [ 4,  4,  5,  5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10, 10, 11, 11]])