In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
# 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
print(type(b))

<class 'numpy.ndarray'>


In [5]:
# 3D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(type(c))
print(np.ndim(c))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
3


In [6]:
d = np.array([1,2,3,4],dtype = bool)
print(d)

[ True  True  True  True]


In [7]:
f = np.arange(30,50).reshape(2,10)
print(f)
x = np.arange(12,24).reshape(3,4)
x

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.random.random((3,4))

array([[0.65828033, 0.86577919, 0.0707178 , 0.28563115],
       [0.58540758, 0.59345801, 0.71576242, 0.03653757],
       [0.03488799, 0.96178251, 0.40526468, 0.21550548]])

In [10]:
np.linspace(10,20,5) # parimeters = first=start, second=last,third=number of items

array([10. , 12.5, 15. , 17.5, 20. ])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# if you givr argument in arange(12) it consider last item which not be include
a1 = np.arange(12,dtype=float).reshape(3,4)
a1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [13]:
# in arange(first=start,second=end,third=jump) 
s1 = np.arange(12,40,3,dtype=float)
s1

array([12., 15., 18., 21., 24., 27., 30., 33., 36., 39.])

In [14]:
np.arange(0,5,0.5,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.arange(-3,3,0.5,dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [16]:
a1.ndim

2

In [17]:
a2 = np.arange(8).reshape(2,2,2)
a2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
s2 = np.arange(24).reshape(1,6,4)
s2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
a1.shape

(3, 4)

In [20]:
a2.shape

(2, 2, 2)

In [21]:
a1.size

12

In [22]:
a2.size

8

In [23]:
a1.itemsize

8

In [24]:
a2.itemsize

8

In [25]:
a1.dtype

dtype('float64')

In [26]:
a2.dtype

dtype('int64')

In [27]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [28]:
a2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
a2.dtype

dtype('int64')

In [30]:
d = a2.astype(np.int32)

In [31]:
d.dtype

dtype('int32')

In [32]:
a4 = np.arange(1,13).reshape(3,4)
a5 = np.arange(13,25).reshape(3,4)
a6 = a4*a5
a6



array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [33]:
a6 = a4*a5
a6

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [34]:
a7 = 4 * a5
a7

array([[52, 56, 60, 64],
       [68, 72, 76, 80],
       [84, 88, 92, 96]])

In [35]:
a7 > 33

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
a7 == 40

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [37]:
np.sum(a7)

np.int64(888)

In [38]:
ak = np.random.random((6,3))
ak

array([[0.35515611, 0.38418553, 0.71597622],
       [0.68653246, 0.53529068, 0.48190184],
       [0.69643688, 0.7236319 , 0.17871701],
       [0.24894365, 0.47016187, 0.14281042],
       [0.24589429, 0.89191248, 0.4775727 ],
       [0.55548636, 0.16023301, 0.14444476]])

In [39]:
ck = np.array([0.45533])
np.round(ck)

array([0.])

In [40]:
np.round(ck*100)

array([46.])

In [41]:
ak = np.random.random((3,3))
ak = np.round(ak*100)
ak

array([[73., 14., 31.],
       [86., 47., 52.],
       [25., 77., 97.]])

In [42]:
ak = np.max(ak)
ak

np.float64(97.0)

In [46]:
np.max(ak,axis=0)




np.float64(97.0)

In [43]:
np.max?

Signature:      
np.max(
    a,
    axis=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Call signature:  np.max(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function max at 0x0000027990B3C4A0>
File:            c:\users\hp\anaconda3\lib\site-packages\numpy\_core\fromnumeric.py
Docstring:      
Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See :ref:`ufuncs-output-type` for more details.

keepdims : bool, 

In [47]:
np.min(ak,axis=0)


np.float64(97.0)

In [53]:
a9 = np.arange(24).reshape(6,4)
a9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
a9 = np.min(a9,axis=1)
a9

array([ 0,  4,  8, 12, 16, 20])

In [55]:
np.sum(a9)

np.int64(60)

In [56]:
np.prod(a9)

np.int64(0)

In [57]:
np.mean(a9)

np.float64(10.0)

In [58]:
np.median(a9)

np.float64(10.0)

In [59]:
np.var(a9)

np.float64(46.666666666666664)

In [60]:
np.std(a9)

np.float64(6.831300510639732)

In [61]:
np.sin(a9)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [62]:
np.cos(a9)

array([ 1.        , -0.65364362, -0.14550003,  0.84385396, -0.95765948,
        0.40808206])

In [63]:
np.tan(a9)

array([ 0.        ,  1.15782128, -6.79971146, -0.63585993,  0.30063224,
        2.23716094])

In [64]:
c1 = np.arange(12).reshape(3,4)
c2 = np.arange(12,24).reshape(4,3)
c3 = np.dot(c1,c2)
c3

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [65]:
np.log(c1)

C:\Users\HP\AppData\Local\Temp\ipykernel_11400\36255721.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(c1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [57]:
np.exp(c1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [66]:
c4 = np.random.random(12).reshape(3,4)
c4 = np.round(c4*100)

c4

array([[10., 17., 71., 13.],
       [74., 81., 28., 44.],
       [57., 36., 62., 20.]])

In [59]:
np.random.random((2,3))

array([[0.87146506, 0.483572  , 0.91728914],
       [0.42377654, 0.81164611, 0.23831172]])

In [67]:
c1 = np.arange(1,5).reshape(2,2)
c2 = np.arange(5,9).reshape(2,2)
c3 = np.dot(c1,c2)
c3

array([[19, 22],
       [43, 50]])

In [68]:
x1 = np.arange(1,5).reshape(2,2)
x2 = np.arange(5,9).reshape(2,2)
x3 =(c1*c2)
x3

array([[ 5, 12],
       [21, 32]])

In [62]:
x3 = np.prod(x1*x2)
x3

np.int64(40320)

In [69]:
s1 = np.arange(12)
s2 = np.arange(12).reshape(3,4)
s3 = np.arange(12,20).reshape(2,2,2)


In [70]:
s1[-1]

np.int64(11)

In [71]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
s2[2,3] #  s2[row,col]

np.int64(11)

In [72]:
s3

array([[[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [68]:
s3[1,1,0] #s3[block,row,col]

np.int64(18)

In [73]:
s4 = np.arange(16).reshape(2,2,2,2)
s4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [121]:
s4[1,1,1,0] #s2[3d block,2d block,row,col]

np.int64(14)

In [80]:
# slicing 
s1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [123]:
s1[3:11] # s1[start:END]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
s2[:2,1:3] #[stars:end for row,start:end for col]

array([[1, 2],
       [5, 6]])

In [68]:
s2[::2,0::2] #[start::2<----jump,start::2<----jump]

array([[ 0,  2],
       [ 8, 10]])

In [82]:
s2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [83]:
s2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [84]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
s2[:,:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [86]:
s2[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
s2[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [88]:
s2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
s2[1:,::3]

array([[ 4,  7],
       [ 8, 11]])

In [90]:
s2[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [91]:
s2[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [92]:
s2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

s2

In [93]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
s2[:,0::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [95]:
s2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [96]:
s2[1,0:]

array([4, 5, 6, 7])

s2[0,1:]

In [97]:
s2[0,1:]

array([1, 2, 3])

In [98]:
s2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [99]:
s3 = np.arange(27).reshape(3,3,3)
s3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [143]:
s3[1] #s3[2d block]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [91]:
s3[::2,0,::2]  #[2d block,row,col] you can jump also

array([[ 0,  2],
       [18, 20]])

In [105]:
# if run loop on 2d array its return all rows  as 1d array
for i in a1:
    print(i[0])

0.0
4.0
8.0


# Iterating


In [150]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [113]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [119]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [156]:
for i in a3:    # in 3d array loop run every bock indexing 
    print(i[2])

[6 7 8]
[15 16 17]
[24 25 26]


In [157]:
for i in np.nditer(a3):  # nditer-----> firt convert in 1d array than loop run
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [163]:
for i in np.ravel(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


## Reshaping

In [120]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Transpose

In [121]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [159]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [122]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Ravel

In [123]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [130]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# stacking

In [126]:
# horizontal stacking
b1 = np.arange(12).reshape(3,4)
b2 = np.arange(12,24).reshape(3,4)
np.hstack((b1,b2,b1))


array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [127]:
# vertical stacking
np.vstack((b1,b2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# spiltting

In [129]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
# horizontal spiltting
np.hsplit(b1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [130]:
# vertical spiltting
b1 = np.arange(12).reshape(4,3)

np.vsplit(b1,2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]