In [1]:
import numpy as np

### `Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


In [2]:
a = np.random.randint(0,100,(3,4))

In [3]:
a

array([[ 8, 24, 27, 24],
       [14, 26,  9, 63],
       [58, 93, 41, 73]], dtype=int32)

In [4]:
# rows wise sort
np.sort(a)

array([[ 8, 24, 24, 27],
       [ 9, 14, 26, 63],
       [41, 58, 73, 93]], dtype=int32)

In [5]:
# columns wise sort
np.sort(a,axis=0)

array([[ 8, 24,  9, 24],
       [14, 26, 27, 63],
       [58, 93, 41, 73]], dtype=int32)

In [9]:
# reverse sort rows wise
np.sort(a)[::-1]

array([[41, 58, 73, 93],
       [ 9, 14, 26, 63],
       [ 8, 24, 24, 27]], dtype=int32)

In [10]:
# colums wise reverse sort
np.sort(a,axis=0)[::-1]

array([[58, 93, 41, 73],
       [14, 26, 27, 63],
       [ 8, 24,  9, 24]], dtype=int32)

In [14]:
a

array([[ 8, 24, 27, 24],
       [14, 26,  9, 63],
       [58, 93, 41, 73]], dtype=int32)

In [28]:
b = np.array([[ 8, 24, 24, 27],
       [ 9, 14, 26, 63],
       [41, 58, 73, 93]])
b

array([[ 8, 24, 24, 27],
       [ 9, 14, 26, 63],
       [41, 58, 73, 93]])

In [33]:
print(np.sort(b[:,1],axis=0))

[14 24 58]


In [34]:
print(b[b[:, 1].argsort()])

[[ 9 14 26 63]
 [ 8 24 24 27]
 [41 58 73 93]]


In [47]:
b[:, 1].argsort()

array([1, 0, 2])

In [37]:
b[:,1]

array([24, 14, 58])

In [49]:
print(b[b[:, 1].argsort()])

[[ 9 14 26 63]
 [ 8 24 24 27]
 [41 58 73 93]]
