In [3]:
import numpy as np

#### Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [20]:
a = np.nan * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### Q-2 Ask user to input two numbers a, b.
### Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [32]:
a,b = map(int,input("Enter two numbers").split())
x = np.random.randint(1,100,size=(a,b))
print(x)
print("Mean:", np.mean(x))

Enter two numbers 3 4


[[82 30 92 43]
 [71 99 59 44]
 [ 9  1  3 50]]
Mean: 48.583333333333336


### Q-3Write a function to create a 2d array with 1 on the border and 0 inside. 
### Take 2-D array shape as (a,b) as parameter to function.

In [48]:
def border_array(a,b):
    x = np.ones((a,b))
    x[1:-1,1:-1] = 0
    return x
border_array(6,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [53]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###  Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [59]:
# identity mattrix must same row and columns. thats why this is not possible shape of 3x4
# np.eye and np.identity are same
print(np.eye(3))
np.identity(4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [62]:
z = np.zeros((5,5))
z += np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [64]:
np.arange(5) + z

array([[0., 2., 4., 6., 8.],
       [0., 2., 4., 6., 8.],
       [0., 2., 4., 6., 8.],
       [0., 2., 4., 6., 8.],
       [0., 2., 4., 6., 8.]])

### Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

In [66]:
import numpy as np

coords = np.random.randint(1, 101, size=(10, 2))
point = np.array([20, 30])

distances = np.sqrt(np.sum((coords - point)**2, axis=1)).astype(int)

print("Coordinates:\n", coords)
print("Given point:", point)
print("Distances:", distances)


Coordinates:
 [[46 59]
 [18 11]
 [27 39]
 [55 57]
 [70 71]
 [83 35]
 [23 52]
 [85 26]
 [62 84]
 [76 58]]
Given point: [20 30]
Distances: [38 19 11 44 64 63 22 65 68 62]


### Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?



In [71]:
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))

### Q-9: Arrays
You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

Input Format:

A single line of input containing space separated numbers.

Output Format:

Print the reverse NumPy array with type float.

Example 1:

Input:

1 2 3 4 -8 -10

In [6]:
a = input().strip().split()

 1 3 4 6 -5


In [7]:
np.array(a[::-1],dtype=float)

array([-5.,  6.,  4.,  3.,  1.])

### Q-10: Elements count
Count the number of elements of a numpy array.

Example 1:

Input:

np.array([])
Output:

elements_count :  0
Example 2:

Input:

np.array([1, 2])
Output:

elements_count :  2

In [12]:
a = np.array([])
a = np.array([1,2])
a = np.zeros((2,3))
a.size

6

### Q-11: Softmax function
Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.



https://en.wikipedia.org/wiki/Softmax_function


In [16]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires numpy array")
    elif arr.ndim > 1:
        raise TypeError("require 1d Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s
softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

In [15]:
#Code here
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s
softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



In [36]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Require a array")
    return np.vstack(args)
a = np.arange(10).reshape(2,-1)
print("a=",a)
b = np.repeat(1,10).reshape(2,-1)
print("b=",b)
print(vertical_stack(a,b))
c = np.random.random((2,5))
print("c=",c)
print(vertical_stack(a,b,c))

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.07118271 0.95674877 0.33292337 0.98377664 0.14633474]
 [0.64359228 0.19357993 0.58147931 0.66834424 0.99709448]]
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.07118271 0.95674877 0.33292337 0.98377664 0.14633474]
 [0.64359228 0.19357993 0.58147931 0.66834424 0.99709448]]


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
None


In [28]:
np.repeat(1,10).reshape(2,-1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
#Code here

def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError
        
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1
    
    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end 
date_array(start = '2020-12-25', end = '2021-01-30')

array(['2020-12-25', '2020-12-26', '2020-12-27', '2020-12-28',
       '2020-12-29', '2020-12-30', '2020-12-31', '2021-01-01',
       '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05',
       '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09',
       '2021-01-10', '2021-01-11', '2021-01-12', '2021-01-13',
       '2021-01-14', '2021-01-15', '2021-01-16', '2021-01-17',
       '2021-01-18', '2021-01-19', '2021-01-20', '2021-01-21',
       '2021-01-22', '2021-01-23', '2021-01-24', '2021-01-25',
       '2021-01-26', '2021-01-27', '2021-01-28', '2021-01-29',
       '2021-01-30'], dtype='datetime64[D]')

### Q-14: Subtract the mean of each row from a matrix.

In [39]:
#code here
x = np.random.random((5,4))
x - x.mean(axis = 1, keepdims = True)

array([[-0.08470366, -0.17366167, -0.07283258,  0.3311979 ],
       [-0.4023237 , -0.15139728,  0.40261483,  0.15110616],
       [-0.01642914, -0.27851948,  0.32976015, -0.03481153],
       [ 0.09804869, -0.342101  ,  0.42009286, -0.17604055],
       [ 0.18241126, -0.47981841,  0.17714163,  0.12026551]])

### Q-15: Swap column-1 of array with column-2 in the array.

In [41]:
#Code here
a = np.arange(9).reshape(3,3)
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
#Code here

a[:, [0, 2, 1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [44]:
a[:,[2,0,1]]

array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

### Q-16: Replace odd elements in arrays with -1.

In [45]:
a = np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
a[a%2 !=0] = -1
a

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8]])

### Q-17: Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

In [50]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])